package knu.database.musebase.console;

public enum PageKey {
    MAIN,
    MY_PAGE,
    MY_PAGE_PLAYLIST,
    MY_PAGE_SONG_REQUEST,
    MY_PAGE_COMMENT,

    PLAYLIST_PAGE, SEARCH, EXIT, PLAYLIST_SEARCH, SONG_SEARCH, PLAYLIST_SEARCH_RESULT, ARTIST_SEARCH, ARTIST_RESULT, SONG_RESULT, PLAYLIST_DETAIL, PLAYLIST_DETAIL_MAIN;
}
